apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: test
  labels:
    app: webapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  
  template:
    metadata: 
      labels:
        app: webapp

    
    spec:
      containers:
        - name: nginx
          image: public.ecr.aws/nginx/nginx:1.25.3
          ports:
            - containerPort: 80