name: Minimal DevOps CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ansible:
    name: Ansible Deploy (Local Simulation)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Playbook (simulate localhost)
        run: ansible-playbook -i inventory.ini copy_index.yml

  kubernetes:
    name: Kubernetes Deploy
    runs-on: ubuntu-latest
    needs: ansible
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0'

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Apply Manifests
        run: kubectl apply -f k8s/